:bug: skip verif when merging

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -21,9 +21,12 @@ jobs:
           run: |
             COMMIT_NAME=$(git log --format=%s -n 1)
             echo "Commit name: $COMMIT_NAME"
-            if [[ ! $COMMIT_NAME =~ ^:[a-z_]+: ]]; then
-              echo "::error title=Invalid commit name::Commit name must start with a gitmoji"
-              exit 1
+            
+            if [[ ! $COMMIT_NAME =~ ^Merge ]]; then
+              if [[ ! $COMMIT_NAME =~ ^:[a-z_]+: ]]; then
+                echo "::error title=Invalid commit name::Commit name must start with a gitmoji"
+                exit 1
+              fi
             fi
   push_to_mirror:
     name: push to mirror
